//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/GameFolder/01_Scripts/b_PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @B_PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @B_PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""b_PlayerController"",
    ""maps"": [
        {
            ""name"": ""PlayerBaseController"",
            ""id"": ""333acde8-ca9e-46a6-925d-b32e65099349"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bcf9595d-125b-4c8b-982e-3f83a64a72e4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateRight"",
                    ""type"": ""Button"",
                    ""id"": ""d09bc6e4-859c-4038-ba9b-25e4dcc59368"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""d079196f-bf78-4ae7-b8d1-2075d132fb68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""3f5af270-1609-4c56-a65e-e6a3dffae0f1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3f232a4f-21e1-4ade-9c7a-630118e36ed0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e455a704-49ba-4ce2-9d7b-b6f3d5e974f8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""693c6e80-de32-4add-a623-e459a295ff46"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8bd9c1d5-c8ce-4f93-b20e-8da74601c858"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""34c9f395-af33-4ede-b9e8-f4f58376fc15"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fa6ad8b-9a8a-48dc-b7b6-3912db997b0c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbb3ed4c-4c8d-4fb1-bdda-6af7c9858747"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerBaseController
        m_PlayerBaseController = asset.FindActionMap("PlayerBaseController", throwIfNotFound: true);
        m_PlayerBaseController_Move = m_PlayerBaseController.FindAction("Move", throwIfNotFound: true);
        m_PlayerBaseController_RotateRight = m_PlayerBaseController.FindAction("RotateRight", throwIfNotFound: true);
        m_PlayerBaseController_RotateLeft = m_PlayerBaseController.FindAction("RotateLeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerBaseController
    private readonly InputActionMap m_PlayerBaseController;
    private IPlayerBaseControllerActions m_PlayerBaseControllerActionsCallbackInterface;
    private readonly InputAction m_PlayerBaseController_Move;
    private readonly InputAction m_PlayerBaseController_RotateRight;
    private readonly InputAction m_PlayerBaseController_RotateLeft;
    public struct PlayerBaseControllerActions
    {
        private @B_PlayerController m_Wrapper;
        public PlayerBaseControllerActions(@B_PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerBaseController_Move;
        public InputAction @RotateRight => m_Wrapper.m_PlayerBaseController_RotateRight;
        public InputAction @RotateLeft => m_Wrapper.m_PlayerBaseController_RotateLeft;
        public InputActionMap Get() { return m_Wrapper.m_PlayerBaseController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerBaseControllerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerBaseControllerActions instance)
        {
            if (m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnMove;
                @RotateRight.started -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnRotateRight;
                @RotateRight.performed -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnRotateRight;
                @RotateRight.canceled -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnRotateRight;
                @RotateLeft.started -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnRotateLeft;
                @RotateLeft.performed -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnRotateLeft;
                @RotateLeft.canceled -= m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface.OnRotateLeft;
            }
            m_Wrapper.m_PlayerBaseControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @RotateRight.started += instance.OnRotateRight;
                @RotateRight.performed += instance.OnRotateRight;
                @RotateRight.canceled += instance.OnRotateRight;
                @RotateLeft.started += instance.OnRotateLeft;
                @RotateLeft.performed += instance.OnRotateLeft;
                @RotateLeft.canceled += instance.OnRotateLeft;
            }
        }
    }
    public PlayerBaseControllerActions @PlayerBaseController => new PlayerBaseControllerActions(this);
    public interface IPlayerBaseControllerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotateRight(InputAction.CallbackContext context);
        void OnRotateLeft(InputAction.CallbackContext context);
    }
}
